import { AppProps } from 'next/dist/shared/lib/router/router';
import Head from 'next/head';
import '../styles/globals.css';

const App = ({ Component, pageProps }: AppProps): JSX.Element => {
	return (
		<>
			<Head>
				<title>Top App</title>
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Noto+Sans+Display:wght@300;400;500;700&display=swap"
					rel="stylesheet"
				/>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Component {...pageProps} />
		</>
	);
};

export default App;
